### ISSUE TITLE
Y U CLUTTER GLOBAL OBJECT?

### ISSUE THREAD

**Issue by Zirak** [rlemon/UserScripts#12]
See title. Give good reason or do the unthinkable, and remove useless code.

p.s.:This refers to all the `EmbedFunctionOnPage` things.

**Comment by rlemon** [comment]
I am looking into that now that you have called it out to me. There was an article I read on how to author userscripts that told me to do this and had a very convincing reason. However not being able to find said article; I am going to revisit this logic.

**Comment by Zirak** [comment]
This is 10 years old.

We've known each other for 10 years.

wow.

**Comment by Kamilczak020** [comment]
But has it been fixed????
